apiVersion: v1
kind: Service
metadata:
  labels:
    app: angular
  name: angular-svc-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      nodePort: 30010
  selector:
    app: angular
