apiVersion: v1
kind: Pod
metadata:
  labels:
    app: django
  name: django
  namespace: default
spec:
  containers:
    - name: django
      image: django-example:1.2
      imagePullPolicy: Never # only for local testing, should be removed for production
      ports:
        - containerPort: 8000
          protocol: TCP
